apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qninhq46r-python 
  janus-idp.io/tekton: qninhq46r-python
  backstage.io/kubernetes-id: qninhq46r-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qninhq46r-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml