apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qninhq46r-python
  janus-idp.io/tekton: qninhq46r-python
  backstage.io/kubernetes-id: qninhq46r-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qninhq46r-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
